#!/usr/bin/env node
/**
 * build-dre.cjs — Le os XLSX de DRE (Vical Brasil + Vical Instrumentos)
 * e gera dre-data.js com window.DRE_DATA.
 *
 * Hierarquia:
 *   "01 ...", "02 ..." etc → SECTION HEADER (level 0)
 *   "01.1", "02.1" etc    → SUB-HEADER (level 1)
 *   "01T", "02T" etc      → SUBTOTAL (level 0, isTotal)
 *   outros                → DETAIL (level 2)
 *   "Sem lançamentos"     → skip
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const XLSX = require('xlsx');

const cfg = require('./bi.config.js');
const DRIVE = (cfg.fontes && cfg.fontes.drive && cfg.fontes.drive.base_path) || '';

const FILES = [
  {
    empresa: 'Vical Brasil',
    path: process.env.VICAL_BASES_DIR
      ? path.join(process.env.VICAL_BASES_DIR, 'DRE Vical Brasil.xlsx')
      : path.join(DRIVE, 'DRE Vical Brasil.xlsx'),
  },
  {
    empresa: 'Vical Instrumentos',
    path: process.env.VICAL_BASES_DIR
      ? path.join(process.env.VICAL_BASES_DIR, 'DRE Vical Instrumentos.xlsx')
      : path.join(DRIVE, 'DRE Vical Instrumentos.xlsx'),
  },
];

function parseVal(v) {
  if (v == null || v === '') return 0;
  if (typeof v === 'number') return v;
  // "0,00" or "-1.234,56" → number
  const s = String(v).trim().replace(/\./g, '').replace(',', '.');
  const n = parseFloat(s);
  return isNaN(n) ? 0 : n;
}

function detectLevel(cat) {
  // Subtotal: "01T", "02T", etc
  if (/^\d{2}T\s/.test(cat)) return { level: 0, isTotal: true };
  // Sub-header: "01.1", "02.1", etc
  if (/^\d{2}\.\d/.test(cat)) return { level: 1, isTotal: false };
  // Section header: "01 ", "02 ", etc
  if (/^\d{2}\s/.test(cat)) return { level: 0, isTotal: false };
  // Detail
  return { level: 2, isTotal: false };
}

function parseFile(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`  WARN: ${filePath} nao encontrado — pulando`);
    return { colunas: [], rows: [] };
  }
  const wb = XLSX.readFile(filePath);
  const ws = wb.Sheets[wb.SheetNames[0]];
  const raw = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' });

  if (raw.length < 2) {
    console.warn(`  WARN: ${filePath} vazio ou sem dados`);
    return { colunas: [], rows: [] };
  }

  // Row 1 has column headers: ["Categoria", "Jun/2026", "Jul/2026", "Valor"]
  const headerRow = raw[1];
  const colunas = headerRow.slice(1); // remove "Categoria"

  const rows = [];
  for (let i = 2; i < raw.length; i++) {
    const r = raw[i];
    const cat = String(r[0] || '').trim();
    if (!cat) continue;
    if (cat === 'Sem lançamentos') continue;

    const { level, isTotal } = detectLevel(cat);
    const valores = [];
    for (let c = 1; c < headerRow.length; c++) {
      valores.push(parseVal(r[c]));
    }
    rows.push({ cat, level, isTotal, valores });
  }

  return { colunas, rows };
}

// Main
console.log('[build-dre] Lendo DRE XLSX...');
const empresas = [];
const colunas = [];
const dados = {};

for (const f of FILES) {
  console.log(`  ${f.empresa}: ${f.path}`);
  const result = parseFile(f.path);
  empresas.push(f.empresa);
  dados[f.empresa] = result.rows;
  // Use colunas from first file that has them
  if (colunas.length === 0 && result.colunas.length > 0) {
    colunas.push(...result.colunas);
  }
}

const dreData = { empresas, colunas, dados };

// Write dre-data.js
const outPath = path.join(__dirname, 'dre-data.js');
const js = `// Auto-generated by build-dre.cjs — NÃO EDITE\nwindow.DRE_DATA = ${JSON.stringify(dreData)};\n`;
fs.writeFileSync(outPath, js, 'utf8');

const sizeKB = (js.length / 1024).toFixed(1);
console.log(`[build-dre] OK dre-data.js (${sizeKB} KB) — ${empresas.length} empresas, ${colunas.length} colunas`);
for (const e of empresas) {
  console.log(`  ${e}: ${dados[e].length} linhas`);
}
